-- begin TESTCASCADE_ORDER
alter table TESTCASCADE_ORDER add constraint FK_TESTCASCADE_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references TESTCASCADE_CUSTOMER(ID)^
alter table TESTCASCADE_ORDER add constraint FK_TESTCASCADE_ORDER_ON_ITEM foreign key (ITEM_ID) references TESTCASCADE_ITEM(ID)^
create index IDX_TESTCASCADE_ORDER_ON_CUSTOMER on TESTCASCADE_ORDER (CUSTOMER_ID)^
create index IDX_TESTCASCADE_ORDER_ON_ITEM on TESTCASCADE_ORDER (ITEM_ID)^
-- end TESTCASCADE_ORDER
